    fastrs_url = "127.0.0.1"
    fastrs_port = 9098
    [[ip_config]]
    name="CN"
    ip="127.0.0.1"
    port="80"

    # [[ip_config]]
    # name="TW"
    # ip="192.168.2.2"
    # port="22"

    # [[ip_config]]
    # name="JP"
    # ip="192.168.3.3"
    # port="33"